version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: