apiVersion: v1
kind: Service
metadata:
  name: {{ include "ip-reverse-app.fullname" . }}
  labels:
    {{- include "ip-reverse-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }} 
  ports:
    - port: {{ .Values.service.port }}       
      targetPort: {{ .Values.service.targetPort }} 
      protocol: TCP
      name: http
  selector:
    {{- include "ip-reverse-app.selectorLabels" . | nindent 4 }}
